import 'package:flutter_test/flutter_test.dart';
import 'package:firebase_core/firebase_core.dart';

import 'package:gemini_gpt/main.dart';
import 'package:gemini_gpt/firebase_options.dart'; // generated by flutterfire configure

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  setUpAll(() async {
    // Initialize Firebase once before all tests
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  });

  testWidgets('Shows login prompt when not logged in', (WidgetTester tester) async {
    // Pump app with logged out state
    await tester.pumpWidget(const MyApp(isloggedIn: false));

    // Expect your login screen text
    expect(find.text('Please log in to continue'), findsOneWidget);
  });

  testWidgets('App loads when logged in', (WidgetTester tester) async {
    // Pump app with logged in state
    await tester.pumpWidget(const MyApp(isloggedIn: true));

    // Adjust this based on your app’s actual home screen
    expect(find.byType(MyApp), findsOneWidget);
  });
}
