// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAFJdpcr2pu_dcRQ-kVnCF-WnB9nXL9d-g',
//     appId: '1:822927120312:web:66e902645e793bdd82a14d',
//     messagingSenderId: '822927120312',
//     projectId: 'geminigpt-54461',
//     authDomain: 'geminigpt-54461.firebaseapp.com',
//     storageBucket: 'geminigpt-54461.firebasestorage.app',
//     measurementId: 'G-LJVVTDP58H',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBmZHcaYOUM50R_J3vMpJK8t1RA7ejj5Vw',
//     appId: '1:822927120312:android:e98c3412566407d082a14d',
//     messagingSenderId: '822927120312',
//     projectId: 'geminigpt-54461',
//     storageBucket: 'geminigpt-54461.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBM-SkQvtN6cm9C9rL8QyybDenFfrmFwxU',
//     appId: '1:822927120312:ios:134252236ee1483b82a14d',
//     messagingSenderId: '822927120312',
//     projectId: 'geminigpt-54461',
//     storageBucket: 'geminigpt-54461.firebasestorage.app',
//     iosBundleId: 'com.mycompany.geminigpt',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBM-SkQvtN6cm9C9rL8QyybDenFfrmFwxU',
//     appId: '1:822927120312:ios:685595bd1cdfdb5d82a14d',
//     messagingSenderId: '822927120312',
//     projectId: 'geminigpt-54461',
//     storageBucket: 'geminigpt-54461.firebasestorage.app',
//     iosBundleId: 'com.example.texttoimage',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyAFJdpcr2pu_dcRQ-kVnCF-WnB9nXL9d-g',
//     appId: '1:822927120312:web:54e541971340914982a14d',
//     messagingSenderId: '822927120312',
//     projectId: 'geminigpt-54461',
//     authDomain: 'geminigpt-54461.firebaseapp.com',
//     storageBucket: 'geminigpt-54461.firebasestorage.app',
//     measurementId: 'G-HP6RN1840S',
//   );
// }
